name: &name "pcgnn-dcl"
# train
batch_size: &batch_size 6
epochs: 250
start_epoch: 0
launcher: 'none'
ckpt_save_interval: 4
max_ckpt_save_num: 20

# global settings
input_channels: &input_channels 3

# dataset settings
dataset_type: &dataset_type "ParkingSlotDataset"
data_root: &data_root "D:/Workshop/CV/NSPS/Datasets/bjtu-ps1"
max_points: &max_points 15

data:
  train:
    name: *name
    type: *dataset_type
    root_path: *data_root
    max_points: *max_points
    mode: 'train'
    batch_size: *batch_size
    num_workers: 0

  val:
    name: *name
    type: *dataset_type
    root_path: *data_root
    max_points: *max_points
    mode: 'val'
    batch_size: *batch_size
    num_workers: 0

# model settings
model:
  type: PointDetectorBase
  task: 'point_detection'
  root_path: *data_root
  detector: *name
  backbone: 'VGG16' #  'VGG16', 'Darknet', 'resnet18', 'resnet50'
  max_points: *max_points
  fl_gamma: 1.0
  input_channels: 3
  output_channels: 13
  depth_factor: 32
  feature_map_size: 16
  descriptor_dim: 128

  point_thresh: 0.008
  boundary_thresh: 0.05
  use_mcab_point: False
  use_mcab_descriptor: False
  mcab_layers: 2
  use_gnn: true
 
  graph_encoder:
      type: 'GAT' # DGCNN or GAT
      point_encoder:
          output_dim: 128
          layers: [32, 64] # 32, 64, 128
      gnn:
          k: 10 # for DGCNN
          gat_layers: 3 # for GAT
          proj_dim: 64

  edge_predictor:
      input_dim: 128 # 2 * proj_dim
      layers: [256, 128]

  losses:
      weight_point: 1.0
      weight_edge: 100.0
      weight_angle: 100.0

optimization:
    optimizer: adam_onecycle
    weight_decay: 0.01

    lr: 0.003
    moms: [0.95, 0.85]
    pct_start: 0.4
    div_factor: 10

    grad_norm_clip: 10
