name: &name 'dmpr'
# train
batch_size: &batch_size 8
epochs: 200
start_epoch: 0
launcher: 'none'
ckpt_save_interval: 1
max_ckpt_save_num: 20

# global settings
input_channels: &input_channels 3

# dataset settings
dataset_type: &dataset_type "ParkingSlotDataset"
data_root: &data_root "D:/Workshop/CV/NSPS/Datasets/bjtu-ps1"
max_points: &max_points 15

data:
  train:
    name: *name
    type: *dataset_type
    root_path: *data_root
    max_points: *max_points
    mode: 'train'
    batch_size: *batch_size
    num_workers: 0

  val:
    name: *name
    type: *dataset_type
    root_path: *data_root
    max_points: *max_points
    mode: 'val'
    batch_size: *batch_size
    num_workers: 0


# model settings
model:
  type: PointDetectorBase
  task: 'point_detection'
  root_path: *data_root
  detector: *name
  backbone: 'Darknet' #  'VGG16', 'Darknet', 'resnet18', 'resnet50'
  input_channels: 3
  output_channels: 6 # DMPR: 6, GAT: 3
  depth_factor: 32
  feature_map_size: 16

  point_thresh: 0.008
  boundary_thresh: 0.05

optimization:
    optimizer: adam_onecycle
    weight_decay: 0.01

    lr: 0.003
    moms: [0.95, 0.85]
    pct_start: 0.4
    div_factor: 10

    grad_norm_clip: 10
